---
name: "CI"
on: # yamllint disable-line rule:truthy rule:comments
  - "push"
  - "pull_request"

jobs:
  linting:
    runs-on: "ubuntu-22.04"
    steps:
      # Setup CI environment
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up python"
        id: "setup-python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
      - name: "Set up Poetry"
        uses: "snok/install-poetry@v1"
        with:
          virtualenvs-create: false
          virtualenvs-in-project: true
          installer-parallel: true
      - name: "Install dependencies"
        if: "steps.cached-poetry-dependencies.outputs.cache-hit != 'true'"
        run: "poetry install --no-interaction --no-root"
      # Run linters
      - name: "linting: flake8"
        run: "poetry run invoke flake8"
      - name: "linting: pylint"
        run: "poetry run invoke pylint"
      - name: "linting: yamllint"
        run: "poetry run invoke yamllint"
      - name: "linting: bandit"
        run: "poetry run invoke bandit"
      - name: "linting: ruff"
        run: "poetry run invoke ruff"

  testing:
    needs: "linting"
    runs-on: "ubuntu-22.04"
    steps:
      # Setup CI environment
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up python"
        id: "setup-python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
      - name: "Set up Poetry"
        uses: "snok/install-poetry@v1"
        with:
          virtualenvs-create: false
          virtualenvs-in-project: true
          installer-parallel: true
      - name: "Install dependencies"
        if: "steps.cached-poetry-dependencies.outputs.cache-hit != 'true'"
        run: "poetry install --no-interaction --no-root"
      # Run unittests
      - name: "Testing: unit tests"
        run: "poetry run invoke unittest -v"
